CREATE TABLE USERS(
   ID  SERIAL PRIMARY KEY,
   FIRSTNAME      CHAR(30)      NOT NULL,
   LASTNAME       CHAR(30)       NOT NULL,
   EMAIL          CHAR(50),
   PASSWORD       CHAR(50)
);

CREATE TABLE BOOKS(
   ID  SERIAL PRIMARY KEY,
   TITLE      CHAR(50)      NOT NULL,
   AUTHOR       CHAR(50)       NOT NULL,
   BOOKTEXT          TEXT,
   CATEGORI       INTEGER
);
