DROP TABLE READERPASSPORTS;
DROP TABLE BOOKS;
DROP TABLE USERS;
CREATE TABLE USERS(
   ID  SERIAL NOT NULL PRIMARY KEY,
   FIRSTNAME      VARCHAR(30)      NOT NULL,
   LASTNAME       VARCHAR(30)       NOT NULL,
   EMAIL          VARCHAR(50),
   PASSWORD       VARCHAR(50)
);


CREATE TABLE READERPASSPORTS(
   ID  SERIAL NOT NULL PRIMARY KEY,
   USER_ID INTEGER     REFERENCES USERS (ID),
   ROLE       VARCHAR(30)       NOT NULL,
   STATE          INTEGER NOT NULL
 );


CREATE TABLE BOOKS(
   ID  SERIAL NOT NULL PRIMARY KEY,
   TITLE      VARCHAR(50)      NOT NULL,
   AUTHOR       VARCHAR(50)       NOT NULL,
   BOOKTEXT          TEXT,
   CATEGORI       INTEGER
);

INSERT INTO USERS(FIRSTNAME, LASTNAME, EMAIL, PASSWORD)
VALUES
    ('Mike', 'Lomakin', 'whitelamer@mail.ru', '123456');
INSERT INTO USERS(FIRSTNAME, LASTNAME, EMAIL, PASSWORD)
VALUES
    ('Babulka', 'Zlaya', 'library@mail.ru', '111111');


INSERT INTO READERPASSPORTS(USER_ID, ROLE, STATE)
VALUES
    (1, 'USER', 0);
INSERT INTO READERPASSPORTS(USER_ID, ROLE, STATE)
VALUES
    (2, 'USER', 0);
INSERT INTO READERPASSPORTS(USER_ID, ROLE, STATE)
VALUES
    (2, 'ADMIN', 0);

 select * from USERS u join READERPASSPORTS p on u.id = p.user_id where u.EMAIL='library@mail.ru'